import { createPersistedState } from 'pinia-plugin-persistedstate'

export const pinia = createPinia()
pinia.use(
  createPersistedState({
    auto: false // P1: 关闭全局自动持久化，按需在 store 中开启
  })
)

export { useAdminStore } from './domains/admin/admin'
export { useQuotaStore } from './domains/admin/quota'
export { useAnnouncementStore } from './domains/chat/announcement'
export { useBadgeStore } from './domains/chat/badge'
export { useCapabilityStore } from './domains/chat/capability'
export { useChatStore, useSessionStore } from './domains/chat/chat'
export { useContactStore } from './domains/chat/contacts'
export { useEmojiStore } from './domains/chat/emoji'
export { useGroupStore } from './domains/chat/group'
export { useHistoryStore } from './domains/chat/history'
export { useInitialSyncStore } from './domains/chat/initialSync'
export { useMatrixStore } from './domains/chat/matrix'
export { useMessageStore } from './domains/chat/message'
export { useModerationStore } from './domains/chat/moderation'
export { useNoticeStore } from './domains/chat/notice'
export { useRoomStore } from './domains/chat/room'
export { useSessionUnreadStore } from './domains/chat/sessionUnread'
export { useAlwaysOnTopStore } from './domains/settings/alwaysOnTop'
export { useGuideStore } from './domains/settings/guide'
export { useMenuTopStore } from './domains/settings/menuTop'
export { useMobileStore } from './domains/settings/mobile'
export { usePluginsStore } from './domains/settings/plugins'
export { useSettingStore } from './domains/settings/setting'
export { useSettingsDialogStore } from './domains/settings/settingsDialog'
export { useBotStore } from './domains/user/bot'
export { useLoginHistoriesStore } from './domains/user/loginHistory'
export { useUserStore } from './domains/user/user'
export { useUserMenuStore } from './domains/user/userMenu'
export { useUserStatusStore } from './domains/user/userStatus'
export { useFileStore } from './domains/widget/file'
export { useFileDownloadStore } from './domains/widget/fileDownload'
export { useGlobalStore } from './domains/widget/global'
export { useImageViewer } from './domains/widget/imageViewer'
export { useScannerStore } from './domains/widget/scanner'
export { useSpaceStore } from './domains/widget/space'
export { useSpotlightStore } from './domains/widget/spotlight'
export { useThumbnailCacheStore } from './domains/widget/thumbnailCache'
export { useVideoViewer } from './domains/widget/videoViewer'
