// Existing composables
export { useActionFeedback } from './useActionFeedback'
export { useAriaLive } from './useAriaLive'
export type { AudioExistsResult, AudioFileManagerReturn, FileMetaItem, LocalAudioFile } from './useAudioFileManager'
export { useAudioFileManager } from './useAudioFileManager'
export type { AudioPlaybackReturn } from './useAudioPlayback'
export { useAudioPlayback } from './useAudioPlayback'
export { useCanvasTool } from './useCanvasTool'
export { useCheckUpdate } from './useCheckUpdate'
export type { SelectionRange } from './useCommon'
export { countGraphemes, parseInnerText, useCommon } from './useCommon'
export { useContextMenu } from './useContextMenu'
export { useDownload } from './useDownload'
export type { DriverConfig, DriverStepConfig, UseDriverReturn } from './useDriver'
export { useDriver } from './useDriver'
export { useEventListener } from './useEventListener'
export type { FileUploadItem, FileUploadQueue } from './useFileUploadQueue'
export { globalFileUploadQueue, useFileUploadQueue } from './useFileUploadQueue'
export { useGeolocation } from './useGeolocation'
export { useGlobalShortcut } from './useGlobalShortcut'
export { useImageViewer } from './useImageViewer'
export { useIntersectionTaskQueue } from './useIntersectionTaskQueue'
export type { LinkSegment } from './useLinkSegments'
export { extractLinkSegments, normalizeExternalUrl, openExternalUrl, useLinkSegments } from './useLinkSegments'
// Previously bridged from @/hooks; now native
export { useMitt } from './useMitt'
export type { ConnectionStatus } from './useNetworkStatus'
export { useNetworkStatus } from './useNetworkStatus'
export { useOnlineStatus } from './useOnlineStatus'
export { useOverlayController } from './useOverlayController'
export { usePopover } from './usePopover'
export { useRecentSearchHistory } from './useRecentSearchHistory'
export { useSearchFeedbackSummary } from './useSearchFeedbackSummary'
export { useTauriListener } from './useTauriListener'
export { useTrigger } from './useTrigger'
export type { FileInfoType, UploadOptions } from './useUpload'
export { UploadProviderEnum, useUpload } from './useUpload'
export { useVideoViewer } from './useVideoViewer'
export { useViewport } from './useViewport'
export {
  createWebviewWindow,
  ensureCaptureWindow,
  ensureCheckUpdateWindow,
  ensureNotifyWindow,
  useWindow
} from './useWindow'
